# Generated by Django 2.2 on 2019-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='smalltext',
            field=models.TextField(default='', max_length=80),
        ),
    ]
