# Generated by Django 2.2 on 2019-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_article_smalltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='smalltext',
            field=models.TextField(max_length=80),
        ),
    ]
